---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx-controller-source
  namespace: flux-system
spec:
  interval: 60m0s
  ref:
    branch: main
  url: https://github.com/kubernetes/ingress-nginx
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/ 
