apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: charts/ingress-nginx   # path to the chart within the repo
      version: 4.11.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-controller-source
        namespace: flux-system
      reconcileStrategy: Revision   # good default for Git sources
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
      service:
        type: LoadBalancer