apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
  interval: 30m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: ingress-nginx-controller-source
    namespace: flux-system
  targetNamespace: ingress-nginx
  timeout: 3m0s
  wait: true