---
# Grant permissions in staging (bind flux-system SA to a Role or ClusterRole)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staging-deployer-binding
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin   # or a custom Role with least-privilege
subjects:
- kind: ServiceAccount
  name: staging-flux
  namespace: flux-system  # IMPORTANT: SA is in flux-system
---
# Grant permissions in production
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: production-deployer-binding
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin   # or a custom Role with least-privilege
subjects:
- kind: ServiceAccount
  name: production-flux
  namespace: flux-system  # IMPORTANT: SA is in flux-system
