---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reconciler
  namespace: default
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reconciler-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reconciler
subjects:
- kind: ServiceAccount
  name: flux
  namespace: default
