apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../base/
  - podinfo-kustomization.yaml
  - podinfo-ingress.yaml
namePrefix: production-
patches:
  - target:
      kind: ServiceAccount
      name: flux
      namespace: default
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux
        namespace: production
  - target:
      kind: RoleBinding
      name: reconciler-binding
      namespace: default
    patch: |-
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: production-reconciler
        namespace: production
      subjects:
        - kind: ServiceAccount
          name: production-flux
          namespace: production