apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: production-admin-binding
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: production-flux
  namespace: flux-system