---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system

spec:
  serviceAccountName: staging-flux
  interval: 1m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
  targetNamespace: staging
  timeout: 3m0s
  wait: true
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: podinfo
        metadata:
          namespace: staging
      target:
        kind: Deployment
        name: podinfo
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: podinfo
        metadata:
          namespace: staging
      target:
        kind: Service
        name: podinfo
    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: podinfo
          namespace: staging
        spec:
          minReplicas: 2           
      target:
        name: podinfo
        kind: HorizontalPodAutoscaler
