apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo/overlays/staging/staging-kustomization.yaml
  - podinfo/overlays/production/production-kustomization.yaml
  - podinfo/sources/flux-system/podinfo-source.yaml